version: '3.0'

services:
  email-sender-microservice:
    ports:
      - 8081:8081
    container_name: email-sender-microservice-container
    image: email-sender-microservice-image
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    env_file:
      - local.env
    volumes:
      - "./maven-rep:/root/.m2"
