version: '3.0'

services:
  email-sender-microservice-test:
    ports:
      - 8081:8081
    container_name: email-sender-microservice-test-container
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    env_file:
      - tests.env
    volumes:
      - "./maven-rep:/root/.m2"



  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
