name: auth-microservice
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: docker build -t image  .
      - name: Run docker image
        run: docker run image -e token=${ACCESS_TOKEN}

